/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangxi_ffmpegdemo_VideoUtils */

#ifndef _Included_com_example_wangxi_ffmpegdemo_VideoUtils
#define _Included_com_example_wangxi_ffmpegdemo_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangxi_ffmpegdemo_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_wangxi_ffmpegdemo_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_example_wangxi_ffmpegdemo_VideoUtils_render
        (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_ffmpegdemo_VideoUtils_sound
        (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT void JNICALL Java_com_example_wangxi_ffmpegdemo_VideoUtils_play
        (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
